In [1]:
import pandas as pd
import numpy as np

In [10]:
import pandas as pd
from scipy.sparse import csr_matrix

df = pd.read_csv('wikipedia-vectors.csv', index_col=0)
articles = csr_matrix(df.transpose())
titles = list(df.columns)
df.head()

,HTTP 404,Alexa Internet,Internet Explorer,HTTP cookie,Google Search,Tumblr,Hypertext Transfer Protocol,Social search,Firefox,LinkedIn,...,Chad Kroeger,Nate Ruess,The Wanted,Stevie Nicks,Arctic Monkeys,Black Sabbath,Skrillex,Red Hot Chili Peppers,Sepsis,Adam Levine
0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.008878,0.0,0.0,0.049502,0.000000,0.00000,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00611,0.0
2,0.0,0.029607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00000,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.005646,0.00000,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.00000,0.0

In [3]:
from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans
from sklearn.pipeline import make_pipeline

svd = TruncatedSVD(n_components=50)

kmeans = KMeans(n_clusters=6)

pipeline = make_pipeline(svd, kmeans)

In [4]:
pipeline.fit(articles)

labels = pipeline.predict(articles)

new_df = pd.DataFrame({'label': labels, 'article': titles})

print(new_df.sort_values("label"))

    label                                        article
41      0                                    Hepatitis B
42      0                                    Doxycycline
43      0                                       Leukemia
44      0                                           Gout
45      0                                    Hepatitis C
46      0                                     Prednisone
47      0                                          Fever
48      0                                     Gabapentin
49      0                                       Lymphoma
40      0                                    Tonsillitis
59      1                                    Adam Levine
58      1                                         Sepsis
50      1                                   Chad Kroeger
57      1                          Red Hot Chili Peppers
56      1                                       Skrillex
55      1                                  Black Sabbath
54      1                                 Arctic Monkeys
53      1                                   Stevie Nicks
52      1                                     The Wanted
51      1                                     Nate Ruess
12      2                                   Nigel Lawson
19      2  2007 United Nations Climate Change Conference
18      2  2010 United Nations Climate Change Conference
17      2  Greenhouse gas emissions by the United States
16      2                                        350.org
15      2                                 Kyoto Protocol
10      2                                 Global warming
13      2                               Connie Hedegaard
11      2       Nationally Appropriate Mitigation Action
14      2                                 Climate change
29      3                               Jennifer Aniston
23      3                           Catherine Zeta-Jones
22      3                              Denzel Washington
24      3                                   Jessica Biel
25      3                                  Russell Crowe
26      3                                     Mila Kunis
27      3                                 Dakota Fanning
28      3                                  Anne Hathaway
21      3                             Michael Fassbender
20      3                                 Angelina Jolie
6       4                    Hypertext Transfer Protocol
5       4                                         Tumblr
4       4                                  Google Search
3       4                                    HTTP cookie
2       4                              Internet Explorer
9       4                                       LinkedIn
1       4                                 Alexa Internet
7       4                                  Social search
8       4                                        Firefox
0       4                                       HTTP 404
39      5                                  Franck Ribéry
38      5                                         Neymar
37      5                                       Football
36      5              2014 FIFA World Cup qualification
35      5                Colombia national football team
34      5                             Zlatan Ibrahimović
33      5                                 Radamel Falcao
32      5                                   Arsenal F.C.
30      5                  France national football team
31      5                              Cristiano Ronaldo

In [5]:
from sklearn.decomposition import NMF

In [6]:
model = NMF(n_components=6) 
nmf_features = model.fit_transform(articles)
nmf_features

/usr/local/lib/python3.8/dist-packages/sklearn/decomposition/_nmf.py:289: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.40380942e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.66505045e-01],
       [3.82173768e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.98568589e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.81665158e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.85438900e-01],
       [1.29352287e-02, 1.37950914e-02, 7.76549815e-03, 3.34348482e-02,
        0.00000000e+00, 3.34464293e-01],
       [0.00000000e+00, 0.00000000e+00, 2.06753296e-02, 0.00000000e+00,
        6.04627159e-03, 3.58989165e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.90898177e-01],
       [1.54293449e-02, 1.42820587e-02, 3.76586097e-03, 2.37078120e-02,
        2.62628036e-02, 4.80682410e-01],
       [1.11805183e-02, 3.13762582e-02, 3.09513139e-02, 6.56807000e-02,
        1.96662185e-02, 3.38231074e-01],
       [0.00000000e+00, 0.00000000e+00, 5.30729245e-01, 0.00000000e+00,
        2.83641046e-02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.56513044e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [1.20175243e-02, 6.50380615e-03, 3.12252948e-01, 6.09646456e-02,
        1.13846188e-02, 1.92556376e-02],
       [3.93596758e-03, 6.24597400e-03, 3.42379119e-01, 1.10736551e-02,
        0.00000000e+00, 0.00000000e+00],
       [4.63816266e-03, 0.00000000e+00, 4.34924273e-01, 0.00000000e+00,
        3.84236099e-02, 3.08000657e-03],
       [0.00000000e+00, 0.00000000e+00, 4.83294160e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [5.65227917e-03, 1.83570119e-02, 3.76540380e-01, 3.25391824e-02,
        0.00000000e+00, 1.13307093e-02],
       [0.00000000e+00, 0.00000000e+00, 4.80919846e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.01955162e-03, 5.51014702e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.65974538e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.14153351e-02, 2.08670435e-02, 5.17697714e-01,
        5.81402069e-02, 1.37881957e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.10413318e-01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.60599458e-03, 0.00000000e+00, 4.22327257e-01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.36700752e-01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.98032252e-01,
        0.00000000e+00, 0.00000000e+00],
       [9.88648603e-02, 8.60252367e-02, 3.91376357e-03, 3.80950689e-01,
        4.38436757e-04, 5.22200106e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.72096076e-01,
        0.00000000e+00, 7.14036498e-03],
       [1.31619544e-02, 1.04940001e-02, 0.00000000e+00, 4.68837248e-01,
        0.00000000e+00, 1.16325069e-02],
       [3.86186270e-03, 0.00000000e+00, 0.00000000e+00, 5.75632067e-01,
        0.00000000e+00, 0.00000000e+00],
       [2.26725345e-03, 1.39523921e-03, 0.00000000e+00, 5.27869399e-01,
        1.20263520e-02, 1.49501885e-02],
       [0.00000000e+00, 4.07588073e-01, 1.85707719e-03, 0.00000000e+00,
        2.96579647e-03, 4.50734754e-04],
       [1.53455970e-03, 6.08233543e-01, 5.22552535e-04, 6.24559550e-03,
        1.18435190e-03, 4.38357210e-04],
       [5.39153421e-03, 2.65048518e-01, 5.39824445e-04, 1.86823400e-02,
        6.38601932e-03, 2.89980412e-03],
       [0.00000000e+00, 6.44978035e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.08966179e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.43718218e-01, 0.00000000e+00, 0.00000000e+00,
        3.97723560e-03, 0.00000000e+00],
       [6.10465375e-03, 3.15343206e-01, 1.54878610e-02, 0.00000000e+00,
        5.06241799e-03, 4.74084161e-03],
       [6.48162557e-03, 2.13357415e-01, 9.49763478e-03, 4.56809525e-02,
        1.71895840e-02, 9.51791116e-03],
       [7.99389323e-03, 4.67643500e-01, 0.00000000e+00, 2.43343546e-02,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.42884862e-01, 0.00000000e+00, 2.35398688e-03,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.77065914e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.94241320e-01, 0.00000000e+00],
       [0.00000000e+00, 2.99548230e-04, 2.14670469e-03, 0.00000000e+00,
        3.81759529e-01, 5.83677392e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.64661087e-03,
        5.42218109e-01, 0.00000000e+00],
       [1.78064662e-03, 7.84249455e-04, 1.41648780e-02, 4.60167423e-04,
        4.24282868e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.11375829e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.28543944e-03, 0.00000000e+00,
        3.72867985e-01, 0.00000000e+00],
       [0.00000000e+00, 2.61926129e-04, 3.61138417e-02, 2.32841172e-04,
        2.30498492e-01, 0.00000000e+00],
       [1.12524923e-02, 2.12273850e-03, 1.60990567e-02, 1.02470421e-02,
        3.25445021e-01, 3.75810802e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18939699e-01, 3.57963532e-04],
       [3.08389361e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [3.68201487e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [3.97982759e-01, 2.81748473e-02, 3.67163614e-03, 1.69936214e-02,
        1.95905446e-03, 2.11575058e-02],
       [3.75830342e-01, 2.07652209e-03, 0.00000000e+00, 3.72020709e-02,
        0.00000000e+00, 5.85620598e-03],
       [4.38061348e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [4.57915309e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [2.75511070e-01, 4.47448142e-03, 0.00000000e+00, 5.29433147e-02,
        0.00000000e+00, 1.90936299e-02],
       [4.45228026e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.48543702e-03, 0.00000000e+00],
       [2.92764363e-01, 1.33659810e-02, 1.14269630e-02, 1.05157600e-02,
        1.87687715e-01, 9.23653193e-03],
       [3.78307199e-01, 1.44028842e-02, 0.00000000e+00, 9.84963020e-02,
        1.35884709e-02, 0.00000000e+00]])

In [7]:
from sklearn.preprocessing import normalize

norm_features = normalize(nmf_features)

df = pd.DataFrame(norm_features, index=titles)

article = df.loc["Cristiano Ronaldo"]

similarities = df.dot(article)

print(similarities.nlargest())

Cristiano Ronaldo                1.000000
Franck Ribéry                    0.999972
Radamel Falcao                   0.999942
Zlatan Ibrahimović               0.999942
France national football team    0.999923
dtype: float64